// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $linkedin_index from "./routes/linkedin/index.tsx";
import * as $Jobs from "./islands/Jobs.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/linkedin/index.tsx": $linkedin_index,
  },
  islands: {
    "./islands/Jobs.tsx": $Jobs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
